import tkinter as tk 
from tkinter import *
from tkinter import ttk

window = tk.Tk()
window.title("task1")
window.geometry("650x200")
window.resizable(False,False)

dogphoto = PhotoImage(file="dog.png")
label4 = tk.Label(window, image=dogphoto, borderwidth=3, relief=SUNKEN)
lable3 = tk.Label(window, text="Search By Name", borderwidth=1, relief=SUNKEN)
lable5 = tk.Label(window, text="Cleint Data Base")
entry4 = tk.Entry(window,text="Entry widgets can be typed in", borderwidth=3, relief=SUNKEN)
entry1 = tk.Entry(window,text="Entry widgets can be typed in", borderwidth=3, relief=SUNKEN)
lable1 = tk.Label(window, text="Name")
lable6 = tk.Label(window, text="Breed")
lable7 = tk.Label(window, text="Owner")
lable8 = tk.Label(window, text="Birthdate")
entry2 = tk.Entry(window,text="Entry widgets can be typed in", borderwidth=3, relief=SUNKEN)
lable2 = tk.Label(window, text="Type")
entry3 = tk.Entry(window,text="Entry widgets can be typed in", borderwidth=3, relief=SUNKEN)
entry6 = tk.Entry(window,text="Entry widgets can be typed in", borderwidth=3, relief=SUNKEN)
entry7 = tk.Entry(window,text="Entry widgets can be typed in", borderwidth=3, relief=SUNKEN)
entry8 = tk.Entry(window,text="Entry widgets can be typed in", borderwidth=3, relief=SUNKEN)
entry9 = tk.Entry(window,text="Entry widgets can be typed in", borderwidth=3, relief=SUNKEN)
lable9 = tk.Label(window, text="< Previous", borderwidth=1, relief=SUNKEN)
lable10 = tk.Label(window, text="Next >", borderwidth=1, relief=SUNKEN)
lable11 = tk.Label(window, text="Save Entery", borderwidth=5, relief=SUNKEN)

label4.grid(row = 1, column = 1)
entry1.grid(row=1, column = 5, columnspan=1)
lable3.grid(row = 0, column = 4)
lable5.grid(row = 1, column = 3)
entry1.grid(row=5, column = 1, columnspan=1)
lable1.grid(row = 4, column = 1)
lable6.grid(row = 4, column = 3)
lable7.grid(row = 4, column = 4)
lable8.grid(row = 4, column = 5)
entry2.grid(row=5, column = 3, columnspan=1)
lable2.grid(row = 4, column = 2)
entry3.grid(row=5, column = 3, columnspan=1)
entry6.grid(row=5, column = 2, columnspan=1)
entry7.grid(row=5, column = 4, columnspan=1)
entry8.grid(row=5, column = 5, columnspan=1)
entry9.grid(row=0, column = 5, columnspan=1)
lable9.grid(row = 6, column = 1)
lable10.grid(row = 6, column = 5)
lable11.grid(row = 6, column = 3)
window.mainloop()